"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple, Type, TypeVar, Union
from rcl_interfaces.msg import ListParametersResult, ParameterDescriptor, ParameterValue, SetParametersResult
from rclpy.callback_groups import CallbackGroup
from rclpy.client import Client
from rclpy.clock import Clock
from rclpy.context import Context
from rclpy.event_handler import PublisherEventCallbacks, SubscriptionEventCallbacks
from rclpy.executors import Executor
from rclpy.guard_condition import GuardCondition
from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
from rclpy.parameter import Parameter
from rclpy.publisher import Publisher
from rclpy.qos import QoSProfile
from rclpy.qos_overriding_options import QoSOverridingOptions
from rclpy.service import Service
from rclpy.subscription import Subscription
from rclpy.subscription_content_filter_options import ContentFilterOptions
from rclpy.timer import Rate, Timer
from rclpy.topic_endpoint_info import TopicEndpointInfo
from rclpy.waitable import Waitable

HIDDEN_NODE_PREFIX = ...
MsgType = TypeVar('MsgType')
SrvType = TypeVar('SrvType')
SrvTypeRequest = TypeVar('SrvTypeRequest')
SrvTypeResponse = TypeVar('SrvTypeResponse')
NodeNameNonExistentError = _rclpy.NodeNameNonExistentError
class Node:
    """
    A Node in the ROS graph.

    A Node is the primary entrypoint in a ROS system for communication.
    It can be used to create ROS entities such as publishers, subscribers, services, etc.
    """
    PARAM_REL_TOL = ...
    def __init__(self, node_name: str, *, context: Optional[Context] = ..., cli_args: Optional[List[str]] = ..., namespace: Optional[str] = ..., use_global_arguments: bool = ..., enable_rosout: bool = ..., start_parameter_services: bool = ..., parameter_overrides: Optional[List[Parameter]] = ..., allow_undeclared_parameters: bool = ..., automatically_declare_parameters_from_overrides: bool = ..., enable_logger_service: bool = ...) -> None:
        """
        Create a Node.

        :param node_name: A name to give to this node. Validated by :func:`validate_node_name`.
        :param context: The context to be associated with, or ``None`` for the default global
            context.
        :param cli_args: A list of strings of command line args to be used only by this node.
            These arguments are used to extract remappings used by the node and other ROS specific
            settings, as well as user defined non-ROS arguments.
        :param namespace: The namespace to which relative topic and service names will be prefixed.
            Validated by :func:`validate_namespace`.
        :param use_global_arguments: ``False`` if the node should ignore process-wide command line
            args.
        :param enable_rosout: ``False`` if the node should ignore rosout logging.
        :param start_parameter_services: ``False`` if the node should not create parameter
            services.
        :param parameter_overrides: A list of overrides for initial values for parameters declared
            on the node.
        :param allow_undeclared_parameters: True if undeclared parameters are allowed.
            This flag affects the behavior of parameter-related operations.
        :param automatically_declare_parameters_from_overrides: If True, the "parameter overrides"
            will be used to implicitly declare parameters on the node during creation.
        :param enable_logger_service: ``True`` if ROS2 services are created to allow external nodes
            to get and set logger levels of this node. Otherwise, logger levels are only managed
            locally. That is, logger levels cannot be changed remotely.
        """
        ...
    
    @property
    def publishers(self) -> Iterator[Publisher]:
        """Get publishers that have been created on this node."""
        ...
    
    @property
    def subscriptions(self) -> Iterator[Subscription]:
        """Get subscriptions that have been created on this node."""
        ...
    
    @property
    def clients(self) -> Iterator[Client]:
        """Get clients that have been created on this node."""
        ...
    
    @property
    def services(self) -> Iterator[Service]:
        """Get services that have been created on this node."""
        ...
    
    @property
    def timers(self) -> Iterator[Timer]:
        """Get timers that have been created on this node."""
        ...
    
    @property
    def guards(self) -> Iterator[GuardCondition]:
        """Get guards that have been created on this node."""
        ...
    
    @property
    def waitables(self) -> Iterator[Waitable]:
        """Get waitables that have been created on this node."""
        ...
    
    @property
    def executor(self) -> Optional[Executor]:
        """Get the executor if the node has been added to one, else return ``None``."""
        ...
    
    @executor.setter
    def executor(self, new_executor: Executor) -> None:
        """Set or change the executor the node belongs to."""
        ...
    
    @property
    def context(self) -> Context:
        """Get the context associated with the node."""
        ...
    
    @property
    def default_callback_group(self) -> CallbackGroup:
        """
        Get the default callback group.

        If no other callback group is provided when the a ROS entity is created with the node,
        then it is added to the default callback group.
        """
        ...
    
    @property
    def handle(self): # -> Any:
        """
        Get the handle to the underlying `rcl_node_t`.

        Cannot be modified after node creation.

        :raises: AttributeError if modified after creation.
        """
        ...
    
    @handle.setter
    def handle(self, value):
        ...
    
    def get_name(self) -> str:
        """Get the name of the node."""
        ...
    
    def get_namespace(self) -> str:
        """Get the namespace of the node."""
        ...
    
    def get_clock(self) -> Clock:
        """Get the clock used by the node."""
        ...
    
    def get_logger(self): # -> RcutilsLogger:
        """Get the nodes logger."""
        ...
    
    def declare_parameter(self, name: str, value: Any = ..., descriptor: Optional[ParameterDescriptor] = ..., ignore_override: bool = ...) -> Parameter:
        """
        Declare and initialize a parameter.

        This method, if successful, will result in any callback registered with
        :func:`add_on_set_parameters_callback` and :func:`add_post_set_parameters_callback`
        to be called.

        The name and type in the given descriptor is ignored, and should be specified using
        the name argument to this function and the default value's type instead.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :param value: Value of the parameter to declare.
        :param descriptor: Descriptor for the parameter to declare.
        :param ignore_override: True if overrides shall not be taken into account; False otherwise.
        :return: Parameter with the effectively assigned value.
        :raises: ParameterAlreadyDeclaredException if the parameter had already been declared.
        :raises: InvalidParameterException if the parameter name is invalid.
        :raises: InvalidParameterValueException if the registered callback rejects the parameter.
        """
        ...
    
    def declare_parameters(self, namespace: str, parameters: List[Union[Tuple[str], Tuple[str, Parameter.Type], Tuple[str, Any, ParameterDescriptor],]], ignore_override: bool = ...) -> List[Parameter]:
        """
        Declare a list of parameters.

        The tuples in the given parameter list shall contain the name for each parameter,
        optionally providing a value and a descriptor.
        The name and type in the given descriptors are ignored, and should be specified using
        the name argument to this function and the default value's type instead.
        For each entry in the list, a parameter with a name of "namespace.name"
        will be declared.
        The resulting value for each declared parameter will be returned, considering
        parameter overrides set upon node creation as the first choice,
        or provided parameter values as the second one.

        The name expansion is naive, so if you set the namespace to be "foo.",
        then the resulting parameter names will be like "foo..name".
        However, if the namespace is an empty string, then no leading '.' will be
        placed before each name, which would have been the case when naively
        expanding "namespace.name".
        This allows you to declare several parameters at once without a namespace.

        This method will result in any callback registered with
        :func:`add_on_set_parameters_callback` and :func:`add_post_set_parameters_callback`
        to be called once for each parameter.

        If a callback was registered previously with :func:`add_on_set_parameters_callback`, it
        will be called prior to setting the parameters for the node, once for each parameter.
        If one of the calls due to :func:`add_on_set_parameters_callback` fail, an exception will
        be raised and the remaining parameters will not be declared. Parameters declared up to that
        point will not be undeclared.

        If a callback was registered previously with :func:`add_post_set_parameters_callback`,
        it will be called after setting the parameters successfully for the node,
        once for each parameter.

        This method will `not` result in any callbacks registered with
        :func:`add_pre_set_parameters_callback` to be called.

        :param namespace: Namespace for parameters.
        :param parameters: List of tuples with parameters to declare.
        :param ignore_override: True if overrides shall not be taken into account; False otherwise.
        :return: Parameter list with the effectively assigned values for each of them.
        :raises: ParameterAlreadyDeclaredException if the parameter had already been declared.
        :raises: InvalidParameterException if the parameter name is invalid.
        :raises: InvalidParameterValueException if the registered callback rejects any parameter.
        :raises: TypeError if any tuple in **parameters** does not match the annotated type.
        """
        ...
    
    def undeclare_parameter(self, name: str): # -> None:
        """
        Undeclare a previously declared parameter.

        This method will not cause a callback registered with any of the
        :func:`add_pre_set_parameters_callback`,
        and :func:`add_post_set_parameters_callback` to be called.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :raises: ParameterNotDeclaredException if parameter had not been declared before.
        :raises: ParameterImmutableException if the parameter was created as read-only.
        """
        ...
    
    def has_parameter(self, name: str) -> bool:
        """Return True if parameter is declared; False otherwise."""
        ...
    
    def get_parameter_types(self, names: List[str]) -> List[Parameter.Type]:
        """
        Get a list of parameter types.

        :param names: Fully-qualified names of the parameters to get, including their namespaces.
        :return: The values for the given parameter types.
            A default Parameter.Type.NOT_SET will be returned for undeclared parameters
            if undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and at least one parameter hadn't been declared beforehand.
        """
        ...
    
    def get_parameter_type(self, name: str) -> Parameter.Type:
        """
        Get a parameter type by name.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :return: The type for the given parameter name.
            A default Parameter.Type.NOT_SET will be returned for an undeclared parameter
            if undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and the parameter hadn't been declared beforehand.
        """
        ...
    
    def get_parameters(self, names: List[str]) -> List[Parameter]:
        """
        Get a list of parameters.

        :param names: Fully-qualified names of the parameters to get, including their namespaces.
        :return: The values for the given parameter names.
            A default Parameter will be returned for undeclared parameters if
            undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and at least one parameter hadn't been declared beforehand.
        :raises: ParameterUninitializedException if at least one parameter is statically typed and
            uninitialized.
        """
        ...
    
    def get_parameter(self, name: str) -> Parameter:
        """
        Get a parameter by name.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :return: The value for the given parameter name.
            A default Parameter will be returned for an undeclared parameter if
            undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and the parameter hadn't been declared beforehand.
        :raises: ParameterUninitializedException if the parameter is statically typed and
            uninitialized.
        """
        ...
    
    def get_parameter_or(self, name: str, alternative_value: Optional[Parameter] = ...) -> Parameter:
        """
        Get a parameter or the alternative value.

        If the alternative value is None, a default Parameter with the given name and NOT_SET
        type will be returned if the parameter was not declared.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :param alternative_value: Alternative parameter to get if it had not been declared before.
        :return: Requested parameter, or alternative value if it hadn't been declared before or is
          an uninitialized statically typed parameter.
        """
        ...
    
    def get_parameters_by_prefix(self, prefix: str) -> Dict[str, Optional[Union[bool, int, float, str, bytes, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]]]]:
        """
        Get parameters that have a given prefix in their names as a dictionary.

        The names which are used as keys in the returned dictionary have the prefix removed.
        For example, if you use the prefix "foo" and the parameters "foo.ping", "foo.pong"
        and "bar.baz" exist, then the returned dictionary will have the keys "ping" and "pong".
        Note that the parameter separator is also removed from the parameter name to create the
        keys.

        An empty string for the prefix will match all parameters.

        If no parameters with the prefix are found, an empty dictionary will be returned.

        :param prefix: The prefix of the parameters to get.
        :return: Dict of parameters with the given prefix.
        """
        ...
    
    def set_parameters(self, parameter_list: List[Parameter]) -> List[SetParametersResult]:
        """
        Set parameters for the node, and return the result for the set action.

        If any parameter in the list was not declared beforehand and undeclared parameters are not
        allowed for the node, this method will raise a ParameterNotDeclaredException exception.

        Parameters are set in the order they are declared in the list.
        If setting a parameter fails due to not being declared, then the
        parameters which have already been set will stay set, and no attempt will
        be made to set the parameters which come after.

        If undeclared parameters are allowed, then all the parameters will be implicitly
        declared before being set even if they were not declared beforehand.
        Parameter overrides are ignored by this method.

        This method will result in any callback registered with
        :func:`add_pre_set_parameters_callback`, :func:`add_on_set_parameters_callback` and
        :func:`add_post_set_parameters_callback` to be called once for each parameter.

        If a callback was registered previously with :func:`add_pre_set_parameters_callback`, it
        will be called prior to the validation of parameters for the node, once for each parameter.
        If this callback makes modified parameter list empty, then it will be reflected in the
        returned result; no exceptions will be raised in this case.

        If a callback was registered previously with :func:`add_on_set_parameters_callback`, it
        will be called prior to setting the parameters for the node, once for each parameter.
        If this callback prevents a parameter from being set, then it will be reflected in the
        returned result; no exceptions will be raised in this case.

        If a callback was registered previously with :func:`add_post_set_parameters_callback`,
        it will be called after setting the parameters successfully for the node,
        once for each parameter.

        For each successfully set parameter, a :class:`ParameterEvent` message is
        published.

        If the value type of the parameter is NOT_SET, and the existing parameter type is
        something else, then the parameter will be implicitly undeclared.

        :param parameter_list: The list of parameters to set.
        :return: The result for each set action as a list.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and at least one parameter in the list hadn't been declared beforehand.
        """
        ...
    
    def set_parameters_atomically(self, parameter_list: List[Parameter]) -> SetParametersResult:
        """
        Set the given parameters, all at one time, and then aggregate result.

        If any parameter in the list was not declared beforehand and undeclared parameters are not
        allowed for the node, this method will raise a ParameterNotDeclaredException exception.

        Parameters are set all at once.
        If setting a parameter fails due to not being declared, then no parameter will be set.
        Either all of the parameters are set or none of them are set.

        If undeclared parameters are allowed for the node, then all the parameters will be
        implicitly declared before being set even if they were not declared beforehand.

        This method will result in any callback registered with
        :func:`add_pre_set_parameters_callback` :func:`add_on_set_parameters_callback` and
        :func:`add_post_set_parameters_callback` to be called only once for all parameters.

        If a callback was registered previously with :func:`add_pre_set_parameters_callback`, it
        will be called prior to the validation of node parameters only once for all parameters.
        If this callback makes modified parameter list empty, then it will be reflected in the
        returned result; no exceptions will be raised in this case.

        If a callback was registered previously with :func:`add_on_set_parameters_callback`, it
        will be called prior to setting the parameters for the node only once for all parameters.
        If the callback prevents the parameters from being set, then it will be reflected in the
        returned result; no exceptions will be raised in this case.

        If a callback was registered previously with :func:`add_post_set_parameters_callback`, it
        will be called after setting the node parameters successfully only once for all parameters.

        For each successfully set parameter, a :class:`ParameterEvent` message is published.

        If the value type of the parameter is NOT_SET, and the existing parameter type is
        something else, then the parameter will be implicitly undeclared.

        :param parameter_list: The list of parameters to set.
        :return: Aggregate result of setting all the parameters atomically.
        :raises: ParameterNotDeclaredException if undeclared parameters are not allowed,
            and at least one parameter in the list hadn't been declared beforehand.
        """
        ...
    
    def list_parameters(self, prefixes: List[str], depth: int) -> ListParametersResult:
        """
        Get a list of parameter names and their prefixes.

        :param prefixes: A list of prefixes to filter the parameter names.
            Only the parameter names that start with any of the prefixes are returned.
            If empty, all parameter names are returned.
        :param depth: The depth of nested parameter names to include.
        :return: The list of parameter names and their prefixes.
        :raises: TypeError if the type of any of the passed arguments is not an expected type.
        :raises: ValueError if depth is a negative integer.
        """
        ...
    
    def add_pre_set_parameters_callback(self, callback: Callable[[List[Parameter]], List[Parameter]]) -> None:
        """
        Add a callback gets triggered before parameters are validated.

        Calling this function will add a callback in self._pre_set_parameter_callbacks list.

        This callback can be used to modify the original list of parameters being
        set by the user. The modified list of parameters is then forwarded to the
        "on set parameter" callback for validation.

        The callback takes a list of parameters to be set and returns a list of
        modified parameters.

        One of the use case of "pre set callback" can be updating additional parameters
        conditioned on changes to a parameter.

        All parameters in the modified list will be set atomically.

        Note that the callback is only called while setting parameters with ``set_parameters``,
        ``set_parameters_atomically``, or externally with a parameters service.

        The callback is not called when parameters are declared with ``declare_parameter``
        or ``declare_parameters``.

        The callback is not called when parameters are undeclared with ``undeclare_parameter``.

        An empty modified parameter list from the callback will result in ``set_parameter*``
        returning an unsuccessful result.

        :param callback: The function that is called before parameters are validated.
        """
        ...
    
    def add_on_set_parameters_callback(self, callback: Callable[[List[Parameter]], SetParametersResult]) -> None:
        """
        Add a callback in front to the list of callbacks.

        Calling this function will add a callback in self._on_set_parameter_callbacks list.

        It is considered bad practice to reject changes for "unknown" parameters as this prevents
        other parts of the node (that may be aware of these parameters) from handling them.

        :param callback: The function that is called whenever parameters are being validated
                         for the node.
        """
        ...
    
    def add_post_set_parameters_callback(self, callback: Callable[[List[Parameter]], None]) -> None:
        """
        Add a callback gets triggered after parameters are set successfully.

        Calling this function will add a callback in self._post_set_parameter_callbacks list.

        The callback signature is designed to allow handling of the ``set_parameter*``
        or ``declare_parameter*`` methods. The callback takes a list of parameters that
        have been set successfully.

        The callback can be valuable as a place to cause side effects based on parameter
        changes. For instance updating the internally tracked class attributes once the params
        have been changed successfully.

        :param callback: The function that is called after parameters are set for the node.
        """
        ...
    
    def remove_pre_set_parameters_callback(self, callback: Callable[[List[Parameter]], List[Parameter]]) -> None:
        """
        Remove a callback from list of callbacks.

        Calling this function will remove the callback from self._pre_set_parameter_callbacks list.

        :param callback: The function that is called whenever parameters are set for the node.
        :raises: ValueError if a callback is not present in the list of callbacks.
        """
        ...
    
    def remove_on_set_parameters_callback(self, callback: Callable[[List[Parameter]], SetParametersResult]) -> None:
        """
        Remove a callback from list of callbacks.

        Calling this function will remove the callback from self._parameter_callbacks list.

        :param callback: The function that is called whenever parameters are set for the node.
        :raises: ValueError if a callback is not present in the list of callbacks.
        """
        ...
    
    def remove_post_set_parameters_callback(self, callback: Callable[[List[Parameter]], None]) -> None:
        """
        Remove a callback from list of callbacks.

        Calling this function will remove the callback from self._parameter_callbacks list.

        :param callback: The function that is called whenever parameters are set for the node.
        :raises: ValueError if a callback is not present in the list of callbacks.
        """
        ...
    
    def describe_parameter(self, name: str) -> ParameterDescriptor:
        """
        Get the parameter descriptor of a given parameter.

        :param name: Fully-qualified name of the parameter, including its namespace.
        :return: ParameterDescriptor corresponding to the parameter,
            or default ParameterDescriptor if parameter had not been declared before
            and undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if parameter had not been declared before
            and undeclared parameters are not allowed.
        """
        ...
    
    def describe_parameters(self, names: List[str]) -> List[ParameterDescriptor]:
        """
        Get the parameter descriptors of a given list of parameters.

        :param name: List of fully-qualified names of the parameters to describe.
        :return: List of ParameterDescriptors corresponding to the given parameters.
            Default ParameterDescriptors shall be returned for parameters that
            had not been declared before if undeclared parameters are allowed.
        :raises: ParameterNotDeclaredException if at least one parameter
            had not been declared before and undeclared parameters are not allowed.
        """
        ...
    
    def set_descriptor(self, name: str, descriptor: ParameterDescriptor, alternative_value: Optional[ParameterValue] = ...) -> ParameterValue:
        """
        Set a new descriptor for a given parameter.

        The name in the descriptor is ignored and set to ``name``.

        :param name: Fully-qualified name of the parameter to set the descriptor to.
        :param descriptor: New descriptor to apply to the parameter.
        :param alternative_value: Value to set to the parameter if the existing value does not
            comply with the new descriptor.
        :return: ParameterValue for the given parameter name after applying the new descriptor.
        :raises: ParameterNotDeclaredException if parameter had not been declared before
            and undeclared parameters are not allowed.
        :raises: ParameterImmutableException if the parameter exists and is read-only.
        :raises: ParameterValueException if neither the existing value nor the alternative value
            complies with the provided descriptor.
        """
        ...
    
    def add_waitable(self, waitable: Waitable) -> None:
        """
        Add a class that is capable of adding things to the wait set.

        :param waitable: An instance of a waitable that the node will add to the waitset.
        """
        ...
    
    def remove_waitable(self, waitable: Waitable) -> None:
        """
        Remove a Waitable that was previously added to the node.

        :param waitable: The Waitable to remove.
        """
        ...
    
    def resolve_topic_name(self, topic: str, *, only_expand: bool = ...) -> str:
        """
        Return a topic name expanded and remapped.

        :param topic: Topic name to be expanded and remapped.
        :param only_expand: If ``True``, remapping rules won't be applied.
        :return: A fully qualified topic name,
            the result of applying expansion and remapping to the given ``topic``.
        """
        ...
    
    def resolve_service_name(self, service: str, *, only_expand: bool = ...) -> str:
        """
        Return a service name expanded and remapped.

        :param service: Service name to be expanded and remapped.
        :param only_expand: If ``True``, remapping rules won't be applied.
        :return: A fully qualified service name,
            the result of applying expansion and remapping to the given ``service``.
        """
        ...
    
    def create_publisher(self, msg_type, topic: str, qos_profile: Union[QoSProfile, int], *, callback_group: Optional[CallbackGroup] = ..., event_callbacks: Optional[PublisherEventCallbacks] = ..., qos_overriding_options: Optional[QoSOverridingOptions] = ..., publisher_class: Type[Publisher] = ...) -> Publisher:
        """
        Create a new publisher.

        :param msg_type: The type of ROS messages the publisher will publish.
        :param topic: The name of the topic the publisher will publish to.
        :param qos_profile: A QoSProfile or a history depth to apply to the publisher.
            In the case that a history depth is provided, the QoS history is set to
            KEEP_LAST, the QoS history depth is set to the value
            of the parameter, and all other QoS settings are set to their default values.
        :param callback_group: The callback group for the publisher's event handlers.
            If ``None``, then the default callback group for the node is used.
        :param event_callbacks: User-defined callbacks for middleware events.
        :return: The new publisher.
        """
        ...
    
    def create_subscription(self, msg_type, topic: str, callback: Callable[[MsgType], None], qos_profile: Union[QoSProfile, int], *, callback_group: Optional[CallbackGroup] = ..., event_callbacks: Optional[SubscriptionEventCallbacks] = ..., qos_overriding_options: Optional[QoSOverridingOptions] = ..., raw: bool = ..., content_filter_options: Optional[ContentFilterOptions] = ...) -> Subscription:
        """
        Create a new subscription.

        :param msg_type: The type of ROS messages the subscription will subscribe to.
        :param topic: The name of the topic the subscription will subscribe to.
        :param callback: A user-defined callback function that is called when a message is
            received by the subscription.
        :param qos_profile: A QoSProfile or a history depth to apply to the subscription.
            In the case that a history depth is provided, the QoS history is set to
            KEEP_LAST, the QoS history depth is set to the value
            of the parameter, and all other QoS settings are set to their default values.
        :param callback_group: The callback group for the subscription. If ``None``, then the
            default callback group for the node is used.
        :param event_callbacks: User-defined callbacks for middleware events.
        :param raw: If ``True``, then received messages will be stored in raw binary
            representation.
        :param content_filter_options: The filter expression and parameters for content filtering.
        """
        ...
    
    def create_client(self, srv_type, srv_name: str, *, qos_profile: QoSProfile = ..., callback_group: Optional[CallbackGroup] = ...) -> Client:
        """
        Create a new service client.

        :param srv_type: The service type.
        :param srv_name: The name of the service.
        :param qos_profile: The quality of service profile to apply the service client.
        :param callback_group: The callback group for the service client. If ``None``, then the
            default callback group for the node is used.
        """
        ...
    
    def create_service(self, srv_type, srv_name: str, callback: Callable[[SrvTypeRequest, SrvTypeResponse], SrvTypeResponse], *, qos_profile: QoSProfile = ..., callback_group: Optional[CallbackGroup] = ...) -> Service:
        """
        Create a new service server.

        :param srv_type: The service type.
        :param srv_name: The name of the service.
        :param callback: A user-defined callback function that is called when a service request
            received by the server.
        :param qos_profile: The quality of service profile to apply the service server.
        :param callback_group: The callback group for the service server. If ``None``, then the
            default callback group for the node is used.
        """
        ...
    
    def create_timer(self, timer_period_sec: float, callback: Callable, callback_group: Optional[CallbackGroup] = ..., clock: Optional[Clock] = ..., autostart: bool = ...) -> Timer:
        """
        Create a new timer.

        If autostart is ``True`` (the default), the timer will be started and every
        ``timer_period_sec`` number of seconds the provided callback function will be called.
        If autostart is ``False``, the timer will be created but not started; it can then be
        started by calling ``reset()`` on the timer object.

        :param timer_period_sec: The period (in seconds) of the timer.
        :param callback: A user-defined callback function that is called when the timer expires.
        :param callback_group: The callback group for the timer. If ``None``, then the
            default callback group for the node is used.
        :param clock: The clock which the timer gets time from.
        :param autostart: Whether to automatically start the timer after creation; defaults to
            ``True``.
        """
        ...
    
    def create_guard_condition(self, callback: Callable, callback_group: Optional[CallbackGroup] = ...) -> GuardCondition:
        """Create a new guard condition."""
        ...
    
    def create_rate(self, frequency: float, clock: Optional[Clock] = ...) -> Rate:
        """
        Create a Rate object.

        :param frequency: The frequency the Rate runs at (Hz).
        :param clock: The clock the Rate gets time from.
        """
        ...
    
    def destroy_publisher(self, publisher: Publisher) -> bool:
        """
        Destroy a publisher created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_subscription(self, subscription: Subscription) -> bool:
        """
        Destroy a subscription created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_client(self, client: Client) -> bool:
        """
        Destroy a service client created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_service(self, service: Service) -> bool:
        """
        Destroy a service server created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_timer(self, timer: Timer) -> bool:
        """
        Destroy a timer created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_guard_condition(self, guard: GuardCondition) -> bool:
        """
        Destroy a guard condition created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_rate(self, rate: Rate) -> bool:
        """
        Destroy a Rate object created by the node.

        :return: ``True`` if successful, ``False`` otherwise.
        """
        ...
    
    def destroy_node(self): # -> None:
        """
        Destroy the node.

        Frees resources used by the node, including any entities created by the following methods:

        * :func:`create_publisher`
        * :func:`create_subscription`
        * :func:`create_client`
        * :func:`create_service`
        * :func:`create_timer`
        * :func:`create_guard_condition`

        """
        ...
    
    def get_publisher_names_and_types_by_node(self, node_name: str, node_namespace: str, no_demangle: bool = ...) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered topics for publishers of a remote node.

        :param node_name: Name of a remote node to get publishers for.
        :param node_namespace: Namespace of the remote node.
        :param no_demangle: If ``True``, then topic names and types returned will not be demangled.
        :return: List of tuples.
          The first element of each tuple is the topic name and the second element is a list of
          topic types.
        :raise NodeNameNonExistentError: If the node wasn't found.
        :raise RuntimeError: Unexpected failure.
        """
        ...
    
    def get_subscriber_names_and_types_by_node(self, node_name: str, node_namespace: str, no_demangle: bool = ...) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered topics for subscriptions of a remote node.

        :param node_name: Name of a remote node to get subscriptions for.
        :param node_namespace: Namespace of the remote node.
        :param no_demangle: If ``True``, then topic names and types returned will not be demangled.
        :return: List of tuples.
          The first element of each tuple is the topic name and the second element is a list of
          topic types.
        :raise NodeNameNonExistentError: If the node wasn't found.
        :raise RuntimeError: Unexpected failure.
        """
        ...
    
    def get_service_names_and_types_by_node(self, node_name: str, node_namespace: str) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered service servers for a remote node.

        :param node_name: Name of a remote node to get services for.
        :param node_namespace: Namespace of the remote node.
        :return: List of tuples.
          The first element of each tuple is the service server name
          and the second element is a list of service types.
        :raise NodeNameNonExistentError: If the node wasn't found.
        :raise RuntimeError: Unexpected failure.
        """
        ...
    
    def get_client_names_and_types_by_node(self, node_name: str, node_namespace: str) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered service clients for a remote node.

        :param node_name: Name of a remote node to get service clients for.
        :param node_namespace: Namespace of the remote node.
        :return: List of tuples.
          The first element of each tuple is the service client name
          and the second element is a list of service client types.
        :raise NodeNameNonExistentError: If the node wasn't found.
        :raise RuntimeError: Unexpected failure.
        """
        ...
    
    def get_topic_names_and_types(self, no_demangle: bool = ...) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered topic names and types.

        :param no_demangle: If ``True``, then topic names and types returned will not be demangled.
        :return: List of tuples.
          The first element of each tuple is the topic name and the second element is a list of
          topic types.
        """
        ...
    
    def get_service_names_and_types(self) -> List[Tuple[str, List[str]]]:
        """
        Get a list of discovered service names and types.

        :return: List of tuples.
          The first element of each tuple is the service name and the second element is a list of
          service types.
        """
        ...
    
    def get_node_names(self) -> List[str]:
        """
        Get a list of names for discovered nodes.

        :return: List of node names.
        """
        ...
    
    def get_fully_qualified_node_names(self) -> List[str]:
        """
        Get a list of fully qualified names for discovered nodes.

        Similar to ``get_node_names_namespaces()``, but concatenates the names and namespaces.

        :return: List of fully qualified node names.
        """
        ...
    
    def get_node_names_and_namespaces(self) -> List[Tuple[str, str]]:
        """
        Get a list of names and namespaces for discovered nodes.

        :return: List of tuples containing two strings: the node name and node namespace.
        """
        ...
    
    def get_node_names_and_namespaces_with_enclaves(self) -> List[Tuple[str, str, str]]:
        """
        Get a list of names, namespaces and enclaves for discovered nodes.

        :return: List of tuples containing three strings: the node name, node namespace
            and enclave.
        """
        ...
    
    def get_fully_qualified_name(self) -> str:
        """
        Get the node's fully qualified name.

        :return: Fully qualified node name.
        """
        ...
    
    def count_publishers(self, topic_name: str) -> int:
        """
        Return the number of publishers on a given topic.

        ``topic_name`` may be a relative, private, or fully qualified topic name.
        A relative or private topic is expanded using this node's namespace and name.
        The queried topic name is not remapped.

        :param topic_name: The topic name on which to count the number of publishers.
        :return: The number of publishers on the topic.
        """
        ...
    
    def count_subscribers(self, topic_name: str) -> int:
        """
        Return the number of subscribers on a given topic.

        ``topic_name`` may be a relative, private, or fully qualified topic name.
        A relative or private topic is expanded using this node's namespace and name.
        The queried topic name is not remapped.

        :param topic_name: The topic name on which to count the number of subscribers.
        :return: The number of subscribers on the topic.
        """
        ...
    
    def count_clients(self, service_name: str) -> int:
        """
        Return the number of clients on a given service.

        `service_name` may be a relative, private, or fully qualified service name.
        A relative or private service is expanded using this node's namespace and name.
        The queried service name is not remapped.

        :param service_name: the service_name on which to count the number of clients.
        :return: the number of clients on the service.
        """
        ...
    
    def count_services(self, service_name: str) -> int:
        """
        Return the number of servers on a given service.

        `service_name` may be a relative, private, or fully qualified service name.
        A relative or private service is expanded using this node's namespace and name.
        The queried service name is not remapped.

        :param service_name: the service_name on which to count the number of clients.
        :return: the number of servers on the service.
        """
        ...
    
    def get_publishers_info_by_topic(self, topic_name: str, no_mangle: bool = ...) -> List[TopicEndpointInfo]:
        """
        Return a list of publishers on a given topic.

        The returned parameter is a list of TopicEndpointInfo objects, where each will contain
        the node name, node namespace, topic type, topic endpoint's GID, and its QoS profile.

        When the ``no_mangle`` parameter is ``True``, the provided ``topic_name`` should be a valid
        topic name for the middleware (useful when combining ROS with native middleware (e.g. DDS)
        apps).  When the ``no_mangle`` parameter is ``False``, the provided ``topic_name`` should
        follow ROS topic name conventions.

        ``topic_name`` may be a relative, private, or fully qualified topic name.
        A relative or private topic will be expanded using this node's namespace and name.
        The queried ``topic_name`` is not remapped.

        :param topic_name: The topic_name on which to find the publishers.
        :param no_mangle: If ``True``, ``topic_name`` needs to be a valid middleware topic
            name, otherwise it should be a valid ROS topic name. Defaults to ``False``.
        :return: a list of TopicEndpointInfo for all the publishers on this topic.
        """
        ...
    
    def get_subscriptions_info_by_topic(self, topic_name: str, no_mangle: bool = ...) -> List[TopicEndpointInfo]:
        """
        Return a list of subscriptions on a given topic.

        The returned parameter is a list of TopicEndpointInfo objects, where each will contain
        the node name, node namespace, topic type, topic endpoint's GID, and its QoS profile.

        When the ``no_mangle`` parameter is ``True``, the provided ``topic_name`` should be a valid
        topic name for the middleware (useful when combining ROS with native middleware (e.g. DDS)
        apps).  When the ``no_mangle`` parameter is ``False``, the provided ``topic_name`` should
        follow ROS topic name conventions.

        ``topic_name`` may be a relative, private, or fully qualified topic name.
        A relative or private topic will be expanded using this node's namespace and name.
        The queried ``topic_name`` is not remapped.

        :param topic_name: The topic_name on which to find the subscriptions.
        :param no_mangle: If ``True``, `topic_name` needs to be a valid middleware topic
            name, otherwise it should be a valid ROS topic name. Defaults to ``False``.
        :return: A list of TopicEndpointInfo for all the subscriptions on this topic.
        """
        ...
    
    def wait_for_node(self, fully_qualified_node_name: str, timeout: float) -> bool:
        """
        Wait until node name is present in the system or timeout.

        The node name should be the full name with namespace.

        :param node_name: Fully qualified name of the node to wait for.
        :param timeout: Seconds to wait for the node to be present. If negative, the function
                         won't timeout.
        :return: ``True`` if the node was found, ``False`` if timeout.
        """
        ...
    


